### ISSUE TITLE
Unused/needed code in links_controller

### ISSUE THREAD

**Issue by dummied** [captainclutch96/redditclone#3]
https://github.com/captainclutch96/redditclone/blob/master/app/controllers/links_controller.rb#L84

This is the second student project I've seen this identical method in. Where'd you find it?

Can you explain what it _does_?

**Comment by captainclutch96** [comment]
I created the authorized_user method as a private method so that people couldn't edit links that didn't belong to them already. I also created a before action in the links controller for it. I found it on the Mackenzie Child tutorial.
